// Generated by argus-live.mjs repro 1.1.1 --test: journey order-to-cash, oracle handoff.
// RED until the defect is fixed. Wire signedIn, trigger, fact and mail to this repo's E2E helpers.
import { test, expect } from "@playwright/test";
import type { Browser, BrowserContextOptions, Locator, Page } from "@playwright/test";

const SETTLE = 3000;
const CONTEXT: BrowserContextOptions = {"viewport": {"width": 1440, "height": 900}, "locale": "en-US", "timezoneId": "UTC"};
const marker = `argus-${Date.now().toString(36)}`;

async function signedIn(browser: Browser, account: string, context: BrowserContextOptions): Promise<Page> {
  throw new Error("wire signedIn to this repo's E2E helpers");
}
async function trigger(name: string, values: string[]): Promise<void> {
  throw new Error("wire trigger to this repo's E2E helpers");
}
async function fact(key: string, field: string): Promise<unknown> {
  throw new Error("wire fact to this repo's E2E helpers");
}
async function mail(): Promise<unknown[]> {
  throw new Error("wire mail to this repo's E2E helpers");
}
async function readValue(target: Locator): Promise<string> {
  const v = await target.evaluate((e) => e instanceof HTMLInputElement || e instanceof HTMLTextAreaElement || e instanceof HTMLSelectElement ? e.value : (e as HTMLElement).innerText);
  return v.trim().slice(0, 500);
}

test("order-to-cash: handoff (1.1.1)", async ({ browser }) => {
  const customer1 = await signedIn(browser, "customer.1", CONTEXT);
  const sales1 = await signedIn(browser, "sales.1", CONTEXT);
  await customer1.goto("/orders/new");
  await customer1.getByLabel("Quantity").fill("2");
  await customer1.getByRole("button", {"name": "Place order"}).click();
  const saved_order = await readValue(customer1.getByTestId("order-number"));
  await expect(customer1.getByText(saved_order)).toBeVisible({ timeout: SETTLE });
  await trigger("payment-settles", [saved_order]);
  await expect.poll(() => fact(saved_order, "status"), { timeout: SETTLE }).toBe("paid");
  await sales1.goto("/");
  // final (handoff): the correct behaviour, RED while the defect is there
  await expect(sales1.getByText(saved_order)).toBeVisible({ timeout: SETTLE });
});
